# Generated by Django 5.2.8 on 2025-11-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasave',
            name='session_otp',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='datasave',
            name='user_otp',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
    ]
